[package]
name = "simplex-noise"
version = "0.1.0"
authors = ["Gidaio <killshade@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
rand = "0.7.3"
